services:

  certbot-dns-cloudflare:
    image: certbot/dns-cloudflare
    hostname: certbot-dns-cloudflare
    container_name: certbot-dns-cloudflare
    volumes:
      - ./cloudflare:/opt/cloudflare
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt/log:/var/log/letsencrypt

    # Revoke certificates
    command: >-
      revoke
      --non-interactive
      --cert-name ${DOMAIN}
      --cert-name *.${DOMAIN}
  


