services:

  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx-config:/etc/nginx
      # - ./certs:/etc/ssl/private

  monkeysign1:
    image: monkeysign
    hostname: monkeysign1
    ports:
      - 8081:80

  monkeysign2:
    image: monkeysign
    hostname: monkeysign2
    ports:
      - 8082:80      